language: node_js
sudo: false

cache: yarn

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  name: TravisCI
  on:
    branch: master
